"""Evaluation scenarios for Demo 3 RAG."""

from __future__ import annotations

SCENARIOS: dict[str, dict] = {
    "single_001": {
        "name": "西红柿炒鸡蛋原料和用量",
        "category": "single_doc",
        "question": "西红柿炒鸡蛋需要哪些必备原料？一人份西红柿、鸡蛋和盐大约用多少？",
        "expected_doc_ids": ["vegetable_dish/西红柿炒鸡蛋"],
        "must_contain": ["西红柿", "鸡蛋", "盐"],
        "expected_behavior": "answer",
    },
    "single_002": {
        "name": "金汤力配方",
        "category": "single_doc",
        "question": "金汤力一杯约 350 毫升时，金酒、柠檬汁和冰块分别用多少？",
        "expected_doc_ids": ["drink/金汤力/金汤力"],
        "must_contain": ["金酒", "冰块", "柠檬"],
        "expected_behavior": "answer",
    },
    "single_003": {
        "name": "简易红烧肉调料",
        "category": "single_doc",
        "question": "简易红烧肉里生抽、老抽、料酒和开水分别需要多少？",
        "expected_doc_ids": ["meat_dish/红烧肉/简易红烧肉"],
        "must_contain": ["生抽", "老抽", "料酒", "开水"],
        "expected_behavior": "answer",
    },
    "single_004": {
        "name": "清蒸鲈鱼处理和火候",
        "category": "single_doc",
        "question": "清蒸鲈鱼文档里鲈鱼要怎样腌制、蒸多久，出锅后怎么调味？",
        "expected_doc_ids": ["aquatic/清蒸鲈鱼/清蒸鲈鱼"],
        "must_contain": ["鲈鱼", "10", "蒸鱼豉油"],
        "expected_behavior": "answer",
    },
    "single_005": {
        "name": "酸梅汤原料和煎煮",
        "category": "single_doc",
        "question": "酸梅汤需要哪些主要原料？头煎和二煎分别煮多久？",
        "expected_doc_ids": ["drink/酸梅汤/酸梅汤"],
        "must_contain": ["乌梅", "山楂", "40", "20"],
        "expected_behavior": "answer",
    },
    "single_006": {
        "name": "空气炸锅鸡翅中时间温度",
        "category": "single_doc",
        "question": "空气炸锅鸡翅中怎么解冻和加热？温度、正反面时间分别是多少？",
        "expected_doc_ids": ["semi-finished/空气炸锅鸡翅中/空气炸锅鸡翅中"],
        "must_contain": ["鸡翅", "200", "10", "7"],
        "expected_behavior": "answer",
    },
    "single_007": {
        "name": "葱油用料和炸制",
        "category": "single_doc",
        "question": "葱油需要哪些原料？油、葱、姜、洋葱大约用多少，炸多久？",
        "expected_doc_ids": ["condiment/葱油"],
        "must_contain": ["油", "葱", "姜", "20"],
        "expected_behavior": "answer",
    },
    "single_008": {
        "name": "蛋炒饭关键操作",
        "category": "single_doc",
        "question": "蛋炒饭为什么推荐冷饭？操作里蛋白、蛋黄和米饭的处理顺序是什么？",
        "expected_doc_ids": ["staple/蛋炒饭"],
        "must_contain": ["冷饭", "蛋白", "蛋黄", "米饭"],
        "expected_behavior": "answer",
    },
    "multi_001": {
        "name": "三种鸡蛋羹对比",
        "category": "multi_doc",
        "question": "鸡蛋羹、蒸箱鸡蛋羹和微波炉鸡蛋羹在用水温度或水量、加热工具、时间上有什么不同？",
        "expected_doc_ids": [
            "vegetable_dish/鸡蛋羹/鸡蛋羹",
            "vegetable_dish/鸡蛋羹/蒸箱鸡蛋羹",
            "vegetable_dish/鸡蛋羹/微波炉鸡蛋羹",
        ],
        "must_contain": ["鸡蛋羹", "蒸箱", "微波炉"],
        "expected_behavior": "answer",
    },
    "multi_002": {
        "name": "两种蒸米饭对比",
        "category": "multi_doc",
        "question": "电饭煲蒸米饭和煮锅蒸米饭在水量判断、加热流程和焖饭时间上有什么不同？",
        "expected_doc_ids": ["staple/米饭/电饭煲蒸米饭", "staple/米饭/煮锅蒸米饭"],
        "must_contain": ["米饭", "电饭煲", "煮锅"],
        "expected_behavior": "answer",
    },
    "multi_003": {
        "name": "红烧肉版本对比",
        "category": "multi_doc",
        "question": "简易红烧肉和南派红烧肉在五花肉用量、调料和炖煮时间上有什么区别？",
        "expected_doc_ids": ["meat_dish/红烧肉/简易红烧肉", "meat_dish/红烧肉/南派红烧肉"],
        "must_contain": ["红烧肉", "五花肉"],
        "expected_behavior": "answer",
    },
    "multi_004": {
        "name": "金菲士和金汤力对比",
        "category": "multi_doc",
        "question": "金菲士和金汤力都用金酒，但气泡水、柠檬汁和糖浆用量有什么不同？",
        "expected_doc_ids": ["drink/金菲士/金菲士", "drink/金汤力/金汤力"],
        "must_contain": ["金酒", "气泡水", "柠檬"],
        "expected_behavior": "answer",
    },
    "multi_005": {
        "name": "两种黄油虾对比",
        "category": "multi_doc",
        "question": "黄油煎虾和蒜香黄油虾在虾的处理、黄油用量和调味上有什么差异？",
        "expected_doc_ids": ["aquatic/黄油煎虾/黄油煎虾", "aquatic/蒜香黄油虾/蒜香黄油虾"],
        "must_contain": ["虾", "黄油"],
        "expected_behavior": "answer",
    },
    "multi_006": {
        "name": "糖醋汁和糖醋排骨关系",
        "category": "multi_doc",
        "question": "糖醋汁和糖醋排骨都涉及糖醋调味，它们的糖、醋、生抽或番茄酱用量有什么联系和区别？",
        "expected_doc_ids": ["condiment/糖醋汁", "meat_dish/糖醋排骨/糖醋排骨"],
        "must_contain": ["糖", "醋"],
        "expected_behavior": "answer",
    },
    "none_001": {
        "name": "不存在菜谱",
        "category": "not_found",
        "question": "请给出火星土豆炖月壤的做法。",
        "expected_doc_ids": [],
        "must_contain": ["未找到"],
        "expected_behavior": "not_found",
    },
    "none_002": {
        "name": "精确热量缺失",
        "category": "not_found",
        "question": "简易红烧肉每 100 克的精确热量是多少千卡？",
        "expected_doc_ids": ["meat_dish/红烧肉/简易红烧肉"],
        "must_contain": ["未找到"],
        "expected_behavior": "not_found",
    },
    "none_003": {
        "name": "医疗功效缺失",
        "category": "not_found",
        "question": "酸梅汤能治疗高血压吗？",
        "expected_doc_ids": ["drink/酸梅汤/酸梅汤"],
        "must_contain": ["未找到"],
        "expected_behavior": "not_found",
    },
    "none_004": {
        "name": "不存在设备参数",
        "category": "not_found",
        "question": "用量子烤箱做西红柿炒鸡蛋需要设置多少瓦、几分钟？",
        "expected_doc_ids": ["vegetable_dish/西红柿炒鸡蛋"],
        "must_contain": ["未找到"],
        "expected_behavior": "not_found",
    },
    "ambiguous_001": {
        "name": "鸡蛋羹做法歧义",
        "category": "ambiguous",
        "question": "鸡蛋羹怎么做？",
        "expected_doc_ids": [
            "vegetable_dish/鸡蛋羹/鸡蛋羹",
            "vegetable_dish/鸡蛋羹/蒸箱鸡蛋羹",
            "vegetable_dish/鸡蛋羹/微波炉鸡蛋羹",
        ],
        "must_contain": ["？"],
        "expected_behavior": "clarify",
    },
    "ambiguous_002": {
        "name": "红烧肉做法歧义",
        "category": "ambiguous",
        "question": "红烧肉怎么做？",
        "expected_doc_ids": [
            "meat_dish/红烧肉/简易红烧肉",
            "meat_dish/红烧肉/南派红烧肉",
            "meat_dish/徽派红烧肉/徽派红烧肉",
            "meat_dish/湖南家常红烧肉/湖南家常红烧肉",
        ],
        "must_contain": ["？"],
        "expected_behavior": "clarify",
    },
}
